### ISSUE TITLE
Feature Suggestion: allow profile edit

### ISSUE THREAD

**Issue by PurpleStarChild** [benbrown/shuttlecraft#77] opened 2023-01-01 18:04 UTC
Add an area that allows for setting profile page. This should at minimum include a self description area. 

Optimally it would also allow for listing links and link validation to indicate identity proof.

**Comment by ringtailsoftware** [comment] 2023-01-01 18:42
Adds profile/header image upload and self description editing
https://github.com/benbrown/shuttlecraft/pull/62

**Comment by benbrown** [comment] 2023-01-29 20:05
dupe of #29

**Closed by benbrown** 2023-01-29 20:05 UTC
Labels: enhancement
